### ISSUE TITLE
Uplands with BSL has this bold white area in its skybox that flickers somewhat at night

### ISSUE THREAD

**Issue by Nathan22211** [robotbrain/luminiferous-uplands#40]
![2019-10-11_04 52 49](https://user-images.githubusercontent.com/35241068/66642886-3cb35500-ebe3-11e9-82c1-e59745bbfd31.png)

BSL's the only shader that I know of to have this issue. I can't test out many as I don't have a NIVIDIA or AMD GPU.

**Comment by devvoid** [comment]
After some discussion amongst the Fabric dev-team, we've decided to close this under Won't Fix. Since Optifabric is an unofficial mod that makes an already-closed source mod usable on a mod loader that it was never meant for, there are too many variables at work for us to diagnose the issue. We'll add a message to the README/Curseforge warning about the possible seizure warning.
